### ISSUE TITLE
Warning: array_merge(): Argument #1 is not an array in C:\xampp\htdocs\gal\plugins\piwigo-videojs\admin\admin_sync.php on line 53

### ISSUE THREAD

**Issue by garthski** [xbgmsharp/piwigo-videojs#142]
Warning: array_merge(): Argument #1 is not an array in C:\xampp\htdocs\gal\plugins\piwigo-videojs\admin\admin_sync.php on line 53

Getting this when trying to sync. all input boxes and check boxes etc all blank out too.

**Comment by gammy** [comment]
Hi @garthski, I've had the same problem and this seems to be the same as issue [#130](https://github.com/xbgmsharp/piwigo-videojs/issues/130). Although still not fully resolved (I have some residual issues such as the film effect setting not being stored), have a look at @gadunhas' suggestion from September 14.

**Comment by EddyLB** [comment]
Same issue with version 2.9.b. Any fix?

**Comment by calmor15014** [comment]
I was also getting this issue - error on lines 53 and 58 - and made a few changes to the code to do the unserialize first, check if it's an array, and force it to an array if it's not.  The synchronization works normally afterward.  Example replacement for line 53 (58 similar but not exact):

    $vjs_sync_results = unserialize($conf['vjs_sync']);
    if (!is_array($vjs_sync_results)) {
        $vjs_sync_results = (array)$vjs_sync_results;
    }
    $sync_options = array_merge($vjs_sync_results, $sync_options)

I didn't submit a PR because it's probably not the right way to do it.  I don't know the code well enough to know how to find what sets that value and why it's not an array in the first place.

I could submit a pull request with the changes if it helps.

**Comment by efelon** [comment]
Plugin: 2.9b
Piwigo: 2.9.4
Raspian: Stretch (PHP7.0.30, Nginx 1.10.3, MariaDB 10.1.37)

After the first occurrence of this error I see other problems as well:

- When updating Videos in the batch manager the same error occurred there as well, but only after starting the synchronization once in the plugin admin page (where it occurred as described, but for me on line 78). Before that the batch editing does nothing (no result no errors).

- On the edit page of a single video I cannot enter the "VideoJS" tab any more with the following output. Before that, the tab displayed the correct Video information without error.

```
Warning: array_merge(): Argument #1 is not an array in /var/www/piwigo/plugins/piwigo-videojs/admin/admin_photo.php on line 84

Warning: SimpleXMLElement::__construct(): Entity: line 1: parser error : Start tag expected, '<' not found in /var/www/piwigo/plugins/piwigo-videojs/include/mediainfo.php on line 34

Warning: SimpleXMLElement::__construct(): sh: 1: --Full: not found in /var/www/piwigo/plugins/piwigo-videojs/include/mediainfo.php on line 34

Warning: SimpleXMLElement::__construct(): ^ in /var/www/piwigo/plugins/piwigo-videojs/include/mediainfo.php on line 34
Mediainfo error reading file. Is MediaInfo install? Is MediaInfo in path?
Is the video accessible & readable, Try to run the command manually.
--Full --Output=XML --Language=raw './network/network/2017/12/Foscam_1_2017_12_12.mp4'
output: sh: 1: --Full: not found
```

- When entering the admin synchronization page after the error occurred I immediately get the following error and all check-boxes and text fields are empty.

```
Warning: array_merge(): Argument #1 is not an array in /var/www/piwigo/plugins/piwigo-videojs/admin/admin_sync.php on line 53
```

I started using piwigo only two weeks ago and everything else is working very well. This is just to mention that I personally don't know what the expected behavior would look like in the end for VideoJS. If I would get this plugin up and running my installation and I would be 100% happy.

**Comment by Kernel-Error** [comment]
@calmor15014 
> I could submit a pull request with the changes if it helps.
Yes please. This worked well for me :-)

**Comment by calmor15014** [comment]
@Kernel-Error 

> Yes please. This worked well for me :-)

The user above you mentioned that 2.8b worked, and the plugin is now onto 2.9b so I think the changes are already fixed?

**Comment by garthski** [comment]
So a bit of a delay from above but I after ages of trying to get this working, I actually just decided to uninstall the extension and install it direct from here instead of from the piwigo extension page. It seems there must be some differences between the two.

All I can say is now everything works perfectly and thumbnails/posters are generated when uploading.

**Comment by Scoob79** [comment]
> Hi @garthski, I've had the same problem and this seems to be the same as issue [#130](https://github.com/xbgmsharp/piwigo-videojs/issues/130). Although still not fully resolved (I have some residual issues such as the film effect setting not being stored), have a look at @gadunhas' suggestion from September 14.

Solution 👍 

UPDATE piwigo.piwigo_config SET value='a:0:{}' WHERE piwigo_config.param= 'vjs_sync';

Directly in the database

**Comment by WollyCGN** [comment]
@Scoob79: Thanks, thanks, thanks, long time ago but still works
