### ISSUE TITLE
Error poster running ffmpeg

### ISSUE THREAD

**Issue by kuzco1** [xbgmsharp/piwigo-videojs#42]
Hello,
have done an update to Piwigo 2.7.1 and now I have a problem to create the poster for any *.mp4.
Have also an issue with the mediainfo.

When trying to create the poster
Got the following error:
Mediainfo error reading file: './BilderGalerie/Ausfluege_und_Events/2014/10_19_GutHixholz/2014_10_19_14_51_12_PA191178.mp4'
Error poster running ffmpeg, try it manually: ffmpeg -itsoffset -4 -i './BilderGalerie/Ausfluege_und_Events/2014/10_19_GutHixholz/2014_10_19_14_51_12_PA191178.mp4' -vcodec mjpeg -vframes 1 -an -f rawvideo -y './BilderGalerie/Ausfluege_und_Events/2014/10_19_GutHixholz/pwg_representative/2014_10_19_14_51_12_PA191178.jpg'

When running the ffmpeg manually, I get the error message that the file dos not exists.
'./BilderGalerie/Ausfluege_und_Events/2014/10_19_GutHixholz/2014_10_19_14_51_12_PA191178.mp4': No such file or directory

But it does

Please keep in mind that ./BilderGalerie is a softlink on Windows to a diffrent drive (f:).
With Piwigo 2.6.3 everytghing was fine. I have more than 26k photos and 1k *.mp4.

Using V2.7.a.
ffmpeg.exe (N-50911-g9efcfbe) is installed in c:\piwigo
mediainfo.dll and mediainfo.exe (0.7.70) ) are also installed in c:\piwigo
Checking the  "synchronitazion screen" for this plugin shows me 2 green checkmarks for ffmpeg and mediainfo, so it seems that the plugin has found this tools.

Any hint is welcome.

**Comment by photonensammler** [comment]
thx,

this article was very helpful, my piwiog also working on Windows.

Now I have discovered a new problem (in function_sync2.php):

In videos without exif data occurs a MySql error in the line......

$query = "UPDATE " . IMAGES_TABLE . " SET " . vjs_dbSet($dbfields, $exif) . " ,`date_metadata_update`=CURDATE() WHERE `id`=" . $row['id'] . ";";

.....because the function vjs_dbSet() then returns an empty string or FALSE.
The comma before  `date_metadata_update`= ..... caused the error.

I solved the problem by:

if ($sync_options['metadata'] and ! $sync_options['simulate']) {
          $dbfields = explode(",", "filesize,width,height,latitude,longitude,date_creation,rotation");
//#### this part is changed ####//
          $dbset = vjs_dbSet($dbfields, $exif);
          $dbset= ($dbset !== FALSE && $dbset != '') ?($dbset . ','):'';
          $query = "UPDATE " . IMAGES_TABLE . " SET " . $dbset . " `date_metadata_update`=CURDATE() WHERE `id`=" . $row['id'] . ";";
//#######################//
          //print $query;
          pwg_query($query);

I hope I could help you with this hint !

**Comment by xbgmsharp** [comment]
Can you provide me a video with no metadata. I never saw one.
At least some metadata must be present like ``filesize``, ``width``, ``height``.
Function ``vjs_dbSet`` ensure the field is present prior to generate the SQL query. So it will return an empty string, if none are present. 
However there is check prior. Maybe it is not enough. I commit a change with additional checks.
Please test and report or provide a sample video.

**Comment by photonensammler** [comment]
You're right, all videos have metadata.
The error that widt and height in mysql query are empty, due to the fact that getimagesize() on windows for video files returns no dimensions.
The problem I have solved that I have the function pwg_image_infos ($ path) in functions.upload.inc.php so changed, that ffmpeg is used if getimagesize() does not work properly.
Therefore the comment "with no metadata" is not quite right. 
The customized mysql query but still needed if a user has not installed ffmpeg on windows (which is probably very rarely the case).

**Comment by xbgmsharp** [comment]
Metadata width and height are generated by MediaInfo not by PWG core.
I committed a fix for empty metadata d21f5c8. It ensure there is element in the array.
Please and test and feedback.

**Comment by xbgmsharp** [comment]
Tested on Windows
> I can not find any fault, everything works correctly.
