### ISSUE TITLE
Integration with Modus theme

### ISSUE THREAD

**Issue by alex3137** [xbgmsharp/piwigo-videojs#49]
Hello.

First of all, many thanks for this plugin. I like piwigo-videojs because it enables me to create albums with both photos and videos and it's very easy to use.

I use and love the Modus theme as I find it is elegant and responsive. There is a demo here if you want to see by yourself: http://www.modusoptimus.com/pwg/

I haven't found how to integrate both Modus and piwigo-videojs. Thumbnails page displays fine but videos are always full sized on the picture page and located at the bottom right hand corner.

Is there any way to adapt the video frame to the browser size ? Maybe via some custom CSS ?

It would great to have a play button on the thumbnail page or in diaporama mode.

What do you think ?

**Comment by xbgmsharp** [comment]
Thanks for the support and feedback.

In general,  I try to avoid theme integration.
However a similar issue has been posted on the [PWG forum](http://piwigo.org/forum/viewtopic.php?pid=158069#p158069).

It can be a good time to find a more generic solution.
Would you be able to send video link. I try in the first album but it is only photos.
I would like to see the problem before I install the theme on my dev box.
Hopefully a simple CSS change can do the trick.

Regarding the play button on the thumbnail page or in diaporama mode.
Could please provide a sample or provide mo details.
You want to add a play icon on thumbnail instead of a movie frame?
Or You want to play the video from the thumbnail page?

**Comment by alex3137** [comment]
Hello.

On the thumbnail page, I would love to see a play button + an icon to play it in fullscreen. Same thing in diaporama mode as only the thumbnail is displayed and there is no way to play the video :)

I created a test album on my personnal piwigo with a few photos and video. Is there any chance I can send you a private message with the link of the gallery ?

Thanks !

**Comment by xbgmsharp** [comment]
Yes you Can send me an email.
It is every where in the source code

**Comment by xbgmsharp** [comment]
> On the thumbnail page, I would love to see a play button + an icon to play it in fullscreen.

Would you be able to provide a screenshot of how you want it to be.
I don't understand how you want a play button + an icon to play.
You can have a movie frame to make it look different. How could you see a play button?
Unless you refer to the picture page? not sure it does make sense.

For the diaporama/slideshow request:
> Same thing in diaporama mode as only the thumbnail is displayed and there is no way to play the video :)

I do understand it and it does make sense to autoplay if in slideshow mode.
However it is already the case. unless we don't speak of the same thing.
https://github.com/xbgmsharp/piwigo-videojs/blob/master/main.inc.php#L222
I am not sure about the full-screen maybe via a new option. The slideshow does not display the picture in full screen neither.

I did install the Modus theme and did not see any issue.
![screen shot 2015-03-13 at 4 20 43 pm](https://cloud.githubusercontent.com/assets/1498985/6664697/f36b471a-cbc9-11e4-9198-9a27f759a73d.png)

![screen shot 2015-03-13 at 4 20 54 pm](https://cloud.githubusercontent.com/assets/1498985/6664703/fdcb5d44-cbc9-11e4-966c-3a4c8e80c5f5.png)

**Comment by alex3137** [comment]
Had a few exchanges by email with the developper and my problem was due to an outdate mediainfo version (0.58).

Updating to version 0.70 from Debian backports repo fixed it !
