### ISSUE TITLE
Error: "Warning: Division by zero in . . /plugins/piwigo-videojs/main.inc.php on line 323"

### ISSUE THREAD

**Issue by HyperGlide** [xbgmsharp/piwigo-videojs#59]
After following the installation documents we are receiving the following error:

`Warning: Division by zero in /plugins/piwigo-videojs/main.inc.php on line 323`

When we view a page with a video file.

**Comment by xbgmsharp** [comment]
This message appear because the video is not sync with PWG.
PWG does not know the width and height of the video and the plugin fail to guess the resolution.
You might want to read the requirement and the sync process.
https://github.com/xbgmsharp/piwigo-videojs/wiki/How-to-add-videos#step-3-troubleshoot

If it does not work, you should update the plugin using the git version. A lot a bug have been fixed include default resolution for non sync video.
https://github.com/xbgmsharp/piwigo-videojs/compare/v2.7.a...master

Are you able to see the video details on the photo-edit page in the admin panel?

**Comment by HyperGlide** [comment]
Thanks for the quick response. RTFM. ;-)
