### ISSUE TITLE
H.265 support (successor to H.264/MPEG-4 AVC)

### ISSUE THREAD

**Issue by EddyLB** [xbgmsharp/piwigo-videojs#71]
High Efficiency Video Coding ([HEVC](https://en.wikipedia.org/wiki/High_Efficiency_Video_Coding)) is the next standard and many of us have started using videos compressed with this profile. Would it be possible to implement it ?

**Comment by xbgmsharp** [comment]
Until videojs support H265 it won't be include in the piwigo-videojs.
In general it is not clear if H265 will is the new standard. 
Due to the new licencing model, some commentators have stated that they believe that the licensing costs for the HEVC Advance patent pool might cause companies to switch to competing standards such as Daala and VP9. https://en.wikipedia.org/wiki/High_Efficiency_Video_Coding
http://blog.streamingmedia.com/2015/07/new-patent-pool-wants-share-of-revenue-from-content-owners.html
