### ISSUE TITLE
Add FLV support

### ISSUE THREAD

**Issue by anonsubmitter** [xbgmsharp/piwigo-videojs#82]
Can you add support for the FLV format into piwigo-videojs?

**Comment by xbgmsharp** [comment]
Hello,

The all point of VideoJS is to not use Flash. VideoJS does not support and won't support Flash video Format. Flash is highly deprecated and contain a lot of security issue.
You should transcode your video into a HTML5 format, http://videojs.com/html5-video-support/

**Comment by anonsubmitter** [comment]
HTML5 video players can't play FLV files? Ok. I'd prefer to not have to demux and remux the FLV files, because of archival purposes, but I suppose I have no choice.

**Comment by xbgmsharp** [comment]
Correct, HTML5 video players can't play FLV files.
There are a whole heap of reasons, but ultimately it comes down to a better experience for the user. HTML5 video loads quicker than a Flash plugin and uses less system resources, on top of being much easier to use from a web developer’s standpoint. Mobile devices also have scattered Flash support, but neither iOS or Android (since 4.1) support it.
You would need to transcode your video into a HTML5 format, http://videojs.com/html5-video-support/
You can refer to the wiki to transcode FLV into a HTML5 format.
https://github.com/xbgmsharp/piwigo-videojs/wiki/How-to-add-videos#issue-content-you-know

**Comment by anonsubmitter** [comment]
Yeah, I'll use [tsMuxeR](http://forum.doom9.org/showthread.php?t=168539) and [MP4Box](https://gpac.wp.mines-telecom.fr/mp4box/).
Or would webm be better than mp4? I know at least that mp4 is an old, compatible and reliable format and that webm is the new highly optimized format that big sites have started using in the last few years.

**Comment by xbgmsharp** [comment]
MP4 is supported everywhere, and specially by Google software. However it is not supported by Apple and neither by Microsoft out of the box.
http://www.webmproject.org/users/#supported_web_browsers

Even so I would prefer an OpenSource format, i would raiser use MP4.
