### ISSUE TITLE
MediaInfo version detection broken

### ISSUE THREAD

**Issue by lbeltrame** [xbgmsharp/piwigo-videojs#86]
Example

```
mediainfo --Full --Output=XML --Language=raw 20160522132624-7b74b347.jpg
<?xml version="1.0" encoding="UTF-8"?>
<Mediainfo
    version="0.1"
    ref="20160522132624-7b74b347.jpg">
<File>
```
 And actual version

```
mediainfo --version
MediaInfo Command line, 
MediaInfoLib - v0.7.85
```

The detection thus fails, because it mistakenly assumes that MediaInfo has version 01.

**Comment by xbgmsharp** [comment]
Confirm same issue with version v0.7.86 and v0.7.83.
I suggest you downgrade MediaInfo in the mean time.
I created a bug, https://sourceforge.net/p/mediainfo/bugs/1002/

**Comment by xbgmsharp** [comment]
Bug fixed in MediaInfo v0.7.87, waiting for release.
https://sourceforge.net/p/mediainfo/bugs/1002/
https://github.com/MediaArea/MediaInfoLib/commit/e91d20679599f7fe512b3495cc29d45182882820

**Comment by xbgmsharp** [comment]
An alternative would be to remove the version check.
You can comment the whole ``if`` section.
https://github.com/xbgmsharp/piwigo-videojs/blob/master/include/mediainfo.php#L50

I might add a check to include version "0.1"

**Comment by xbgmsharp** [comment]
I add a warning message if using MediaInfo v0.7.83 to v0.7.86. There is no ETA for v0.7.86 release.
The Wiki has been update accordingly.

**Comment by patmans** [comment]
Updated, and now with:

At commit 434caf35d4f0f543f7f81c2b463bc8e95a9f073e
Author: xbgmsharp <xbgmsharp@gmail.com>
Date:   Wed Jun 15 11:39:43 2016 +0100

    Allow with warning new MediaInfo version #86

And piwigo at 2.8.1, when trying to sync I'm getting:

 Parse error: syntax error, unexpected 'https' (T_STRING) in /home/patman/piwigo/photos/plugins/piwigo-videojs/include/mediainfo.php on line 55

Fixed via (sorry I don't know how you want patches or if you just want pull requests, but it's a trivial fix):

`diff --git a/include/mediainfo.php b/include/mediainfo.php
index 414604e..0942b78 100644
--- a/include/mediainfo.php
+++ b/include/mediainfo.php
@@ -52,7 +52,7 @@ if (isset($xml["version"]))
 {
    if (version_compare($xml["version"], '0.1') == 0)
    {
-       $exif['warning'] = "Please use at least MediaInfo version 0.7.87 or higher, or lower than MediaInfo version 0.7.80 due to known bug: <a href="https://sourceforge.net/p/mediainfo/bugs/1002/" target="_blank">XML output is broken</a>.<br/>Upgrade or downgrade.<br/><a href="https://github.com/xbgmsharp/piwigo-videojs/wiki/How-to-add-videos#external-tools" target="_blank">Please refer to the documentation</a>';";
+       $exif['warning'] = 'Please use at least MediaInfo version 0.7.87 or higher, or lower than MediaInfo version 0.7.80 due to known bug: <a href="https://sourceforge.net/p/mediainfo/bugs/1002/" target="_blank">XML output is broken</a>.<br/>Upgrade or downgrade.<br/><a href="https://github.com/xbgmsharp/piwigo-videojs/wiki/How-to-add-videos#external-tools" target="_blank">Please refer to the documentation</a>';;
    }
    if (version_compare($xml["version"], '0.7.64') < 0)
    {
`

**Comment by patmans** [comment]
That didn't work well, patch is:

diff --git a/include/mediainfo.php b/include/mediainfo.php
index 414604e..0942b78 100644
--- a/include/mediainfo.php
+++ b/include/mediainfo.php
@@ -52,7 +52,7 @@ if (isset($xml["version"]))
 {
    if (version_compare($xml["version"], '0.1') == 0)
    {
-       $exif['warning'] = "Please use at least MediaInfo version 0.7.87 or higher, or lower than MediaInfo version 0.7.80 due to known bug: <a href="https://sourceforge.net/p/mediainfo/bugs/1002/" target="_blank">XML output is broken</a>.<br/>Upgrade or downgrade.<br/><a href="https://github.com/xbgmsharp/piwigo-videojs/wiki/How-to-add-videos#external-tools" target="_blank">Please refer to the documentation</a>';";
+       $exif['warning'] = 'Please use at least MediaInfo version 0.7.87 or higher, or lower than MediaInfo version 0.7.80 due to known bug: <a href="https://sourceforge.net/p/mediainfo/bugs/1002/" target="_blank">XML output is broken</a>.<br/>Upgrade or downgrade.<br/><a href="https://github.com/xbgmsharp/piwigo-videojs/wiki/How-to-add-videos#external-tools" target="_blank">Please refer to the documentation</a>';;
    }
    if (version_compare($xml["version"], '0.7.64') < 0)
    {

**Comment by patmans** [comment]
Oh well, I'm sure you'll figure it out :-)

**Comment by xbgmsharp** [comment]
Should be fix now, thanks for reporting.

**Comment by jradwan** [comment]
I'm getting this message from the plugin when generating thumbnails in Piwigo:

Please use at least MediaInfo version 0.7.64 or higher, not 0.1

My MediaInfo version is 0.7.82. Is this bug related to that message?

**Comment by xbgmsharp** [comment]
MediaInfo version 0.7.83 to 0.7.86 does not present the correct MediaInfo version in the XML output, see https://sourceforge.net/p/mediainfo/bugs/1002/
Apparently MediaInfo version is 0.7.82 is also affected.
There is no ETA for v0.7.87 release, waiting for release.
https://github.com/MediaArea/MediaInfoLib/commit/e91d20679599f7fe512b3495cc29d45182882820

**Comment by xbgmsharp** [comment]
MediaInfo version 0.7.87 is now release.
VideoJs plugin version 2.8.b is now release.
